### ISSUE TITLE
Conversations Not working on CallbackQuery

### ISSUE THREAD

**Issue by hamidqp** [badfarm/zanzara#16]
Hi, today I have noticed that the Conversations feature just works on text messages but I thought they can handle the next Update.

Is there a way to manage all the updates by setting the next step Or it makes deviate from the main purpose of the conversation?

**Comment by cheeghi** [comment]
Hi, yes, conversations are meant to be used with messages only.

**Comment by hamidqp** [comment]
Ok, thanks.

**Comment by cheeghi** [comment]
Hi, in the ```0.6.1``` release we added support for callback queries in conversation

**Comment by musobekmadrimov** [comment]
> Hi, in the `0.6.1` release we added support for callback queries in conversation

Hi, can you give some examples how to use callback queries in conversations, please! Thanks beforehand!
