### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by lamasfoker** [badfarm/zanzara#27]
badfarm/zanzara version 0.6.1

I wrote a symfony command and this is the execute method:
```php
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $bot = $this->zanzaraFactory->create();
        $bot->onCommand('start', function (Context $ctx) {
           // doing stuff
            $ctx->nextStep([$this, 'presentYou']);
        });
    }
```

when `nextStep` is reached I get this Error:
```
Serialization of 'Closure' is not allowed in /Users/**/my-bot/vendor/badfarm/zanzara/src/Zanzara/ConversationManager.php:48
```

I tried this work-around:
```php
$ctx->nextStep(\Closure::fromCallable([$this, 'presentYou']));
```
but another Error has been showed:
```
Call to a member function bindTo() on null in /Users/**/my-bot/vendor/opis/closure/src/SerializableClosure.php:264
```

Sorry for the few details but it is hard to debug asynchronous code.

**Comment by cheeghi** [comment]
Hi, the ```$handler``` passed to ```nextStep``` must be serializable, unfortunately a **Symfony** command extends ```Symfony\Component\Console\Command\Command``` which contains **Closure** properties that make the class not serializable.

I think the cleaner solution is to delegate Zanzara operations to a dedicated class:

```php
class ZanzaraManager
{

    public function presentYou(Context $ctx)
    {
        $ctx->sendMessage('Ok');
    }
}

class ZanzaraCommand extends Command
{

    protected static $defaultName = 'app:zanzara';

    private $zanzaraManager;

    protected function configure()
    {
        $this->zanzaraManager = new ZanzaraManager();
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $bot = $this->zanzaraFactory->create();
        $bot->onCommand('start', function (Context $ctx) {
            // doing stuff
            $ctx->nextStep([$this->zanzaraManager, 'presentYou']);
        });
    }

}
```

So you are sure the ```ZanzaraManager``` class is serializable.

**Comment by lamasfoker** [comment]
Thank you, now it is work!

**Comment by ildarsaitkulov** [comment]
@cheeghi 
I think it is bad idea to serialize conversation handler. I'm using [parallel](https://www.php.net/manual/en/book.parallel.php) it's not being serialized (((

**Comment by cheeghi** [comment]
I'm using parallel -> serializing closure is a bad idea (?) Could you explain it better, maybe providing some code?

**Comment by ildarsaitkulov** [comment]
@cheeghi
```
<?php
class Foo
{
    protected $runtime;
    
    public function __construct()
    {
        $this->runtime = new \parallel\Runtime();
    }
}

$foo = new Foo();
$serialized = serialize($foo);
<--------------------------------------------------------------------------------->
PHP Fatal error:  Uncaught Exception: Serialization of 'parallel\Runtime' is not allowed in .....
```
it's unusual case. But i think in many other cases serialization will not work properly.
I don't know better way how to solve this problem.
Anyway thanks, this awesome library to build telegram bots.

**Comment by cheeghi** [comment]
The solution is the same of this issue: moving the handler in a class that is serializable. Can't you use **parallel** in a class which isn't the one used for conversations..?

**Comment by ildarsaitkulov** [comment]
```
<?php

class Foo
{
    protected $runtime;
    
    public function __construct()
    {
        $this->runtime = new \parallel\Runtime();
    }
}

class Bar
{
    protected $foo;
    
    public function initFoo()
    {
        $this->foo = new Foo();
    }
    
}

$bar = new Bar();
$bar->initFoo();

$serialized = serialize($bar);
<----------------------------------------------------------------------------------->
PHP Fatal error:  Uncaught Exception: Serialization of 'parallel\Runtime' is not allowed 
```
No, I can't. If instance \parallel\Runtime exists, it can't be serialized.

**Comment by cheeghi** [comment]
That's strange, so just if the Runtime class is present (and not serialized) it gives an error? I'll give it a try anyways.
