### ISSUE TITLE
Send message without Context

### ISSUE THREAD

**Issue by MegaBotTeam** [badfarm/zanzara#36]
Hey, how can I send a message without Context (without any listener or anything)?
I want to send a message on every update received from Telegram.

**Comment by cheeghi** [comment]
To send a message on any update just do:
```php

$bot = new Zanzara('token');

$bot->onUpdate(function (Context $ctx) {
    $ctx->sendMessage('Hi');
});

$bot->run();
```

To send messages without listeners:
```php

$bot = new Zanzara('token');

$telegram = $bot->getTelegram();
$telegram->sendMessage('Hi', ['chat_id' => 8662341298]);

$bot->getLoop()->run();
```

**Comment by MegaBotTeam** [comment]
Thanks a lot, I like this library, keep going.
