### ISSUE TITLE
Get chat_id without any Context or Listener

### ISSUE THREAD

**Issue by MegaBotTeam** [badfarm/zanzara#37]
Hello again, sorry for asking too many questions (I am new to this library).
How can I get chat_id outside of any listener or any methods using $bot? 

like this:
```
$chat_id = ?; // I want to get chat_id here

$bot->onUpdate(function (Context $ctx) {
// some codes
});

$bot->onCommand('start', function (Context $ctx) {
// some other codes
});
```

I tried some ways:
```
$chat_id = $bot->getTelegram()->getChat()->getFrom()->getId();  // getChat() needs chat_id, I don't know why.
$chat_id = $bot->getTelegram()->getUpdates()->getFrom()->getId(); // I think it's just for the long polling method.
```

By the way, I use the webhook method.

Also, how can I access the original update (JSON) received from Telegram?

Thanks.

**Comment by cheeghi** [comment]
> How can I get chat_id outside of any listener or any methods using $bot?

You can't. Zanzara is based on reactphp, so when a new update is received from telegram the listeners are executed passing the update to them. To access the update and the **chat_id** do:

```php
$bot->onUpdate(function (Context $ctx) {
    $update = $ctx->getUpdate(); // original update
    $chatId = $ctx->getEffectiveChat()->getId(); // chat_id
});
```

If you give more details on what you want to achieve, we might find a solution.

> Side note: recently we have tested **Zanzara** in webhook mode and we've found that with fpm it doesn't perform well, you will have best results using polling mode or the reactphp-webserver-webhook mode. Anyways, unless your bot doesn't have to handle a lot of traffic I would go with polling mode.

**Comment by MegaBotTeam** [comment]
Thanks for your answer.
Yes, my bot is supposed to have a lot of listeners and traffic.

I also have another problem. sometimes listeners are not executed in order.
For example, ``onMessage()`` and ``onExeption()`` both run, while ``onMessage()`` runs properly until the end.

Is this normal? I thought that after running the bot (``$bot->run()``), if an error occurs in any of the listeners, all operations are canceled, and ``onException()`` is executed.

**Comment by cheeghi** [comment]
> Yes, my bot is supposed to have a lot of listeners and traffic.

Ok, so I suggest you to use the webhook mode with reactphp webserver.

> For example, onMessage() and onExeption() both run, while onMessage() runs properly until the end.

You mean that ```onException()``` is called also when there isn't any error?

**Comment by MegaBotTeam** [comment]
> You mean that `onException()` is called also when there isn't any error?

Yes, why is this happening?

**Comment by MegaBotTeam** [comment]
Thanks for your response.

**Comment by cheeghi** [comment]
I tried it and it doesn't happen to me. Can you provide the minimum code to test the case?

**Comment by MegaBotTeam** [comment]
Sorry for the late response, my problem was solved.
Thanks for your help. keep going, I love your package.
