### ISSUE TITLE
[Request] Support for command parameters

### ISSUE THREAD

**Issue by MegaBotTeam** [badfarm/zanzara#38]
Currently, ``onCommand()`` only supports commands alone and without parameters. I request this feature like this example:
```
/add_admin <chat-id> <roles> <some-other-parameteres>
/ban_user <chat-id>
...
```
I know I can implement these commands using ``onUpdate()`` or listeners or other methods, but it would be great if it was using ``onCommand()`` (As it should be).

**Comment by cheeghi** [comment]
We do support [parameterized commands](https://github.com/badfarm/zanzara/wiki#parameterized-listeners).

**Comment by MegaBotTeam** [comment]
Oh, sorry.
thank you.
