### ISSUE TITLE
Get message_id from sendMessage()

### ISSUE THREAD

**Issue by MegaBotTeam** [badfarm/zanzara#39]
Hey, how can I get ``message_id`` of a message after sending it?
like this:
```
$message = $ctx->sendMessage("Editing message ...");
$message_id = $message->getMessage()->getMessageId(); // What should I do here?
```

And then I want to use it like this:
```
$ctx->editMessageText($message_id, "Message edited successfully.");
```
Maybe this is wrong. I did not find how to do it on the wiki.

You must know that after sending a message (or any other request), Telegram will send the result of this request in response. I want to get this response.
I think it is not possible to do this because of the use of ReactPHP in this library. Am I right?

I know there are many benefits to using ReactPHP, but how I use it confuses me.

Thank you for your effort in this project.

**Comment by bohzio** [comment]
Hi, you can do it like this

```php
  $ctx->sendMessage("Editing message...")->then(function (Message $response) use ($ctx, $bot) {

        $message_id = $response->getMessageId();
        $chat_id = $ctx->getUpdate()->getEffectiveChat()->getId();

        $ctx->editMessageText("Message edited successfully.", ['message_id' => $message_id, 'chat_id' => $chat_id]);
    });

**Comment by MegaBotTeam** [comment]
Thanks for your response.

**Comment by MegaBotTeam** [comment]
Sorry, but it's not working.
Only "Hello" will be sent.

I used the simplest code:
```
$bot->onCommand("start", function (Context $ctx) {
    $ctx->sendMessage('Hello')->then(
        function (Message $message) use ($ctx) {
            $ctx->sendMessage("success");
        },
        function (TelegramException $error) use ($ctx) {
            $ctx->sendMessage("error");
        }
    );
});
```
P.S: I use the webhook mode.
like this:
```
$config->setUpdateMode(Config::WEBHOOK_MODE);
```

**Comment by cheeghi** [comment]
Are ```Message``` and ```TelegramException``` classes imported correctly? They should be ```\Zanzara\Telegram\Type\Message``` and ```\Zanzara\Telegram\Type\Response\TelegramException```

**Comment by MegaBotTeam** [comment]
Oh, I forgot that. Sorry for my stupid questions.
Thanks for your help.
