### ISSUE TITLE
A proposition: rethinking a referenced value from the Polling::startPolling

### ISSUE THREAD

**Issue by itnelo** [badfarm/zanzara#40]
Hey sir! @cheeghi 

Thank you for the efforts on this project. I've used a couple of methods from it for my tasks today and they work very well!

I want to slightly change a `$processingUpdate` workaround for the [Polling](https://github.com/badfarm/zanzara/blob/develop/src/Zanzara/UpdateMode/Polling.php#L57) class, to make a `startPolling` method reference-free. It will help to make, for example, a custom delay between message processing. At the current state, this method is strictly depends on that referenced value. I want to place this logic in the more abstract code unit.

What do you think? Can I provide a pull request for this?

Thanks!

**Comment by cheeghi** [comment]
Hi, you could extend the ```Polling``` class and override the ```startPolling``` method, then you specify your class through the ```Config``` object.  

```php

class MyUpdateProcessor extends \Zanzara\UpdateMode\Polling
{

    public function startPolling()
    {
        // my code
    }

}

$config = new Config();
$config->setUpdateMode(MyUpdateProcessor::class);
$bot = new Zanzara('token', $config);

// ....

$bot->run();

```

**Comment by itnelo** [comment]
That will work for my case, thank you!
