### ISSUE TITLE
ReplyMessages are not routed in conversations nextstep

### ISSUE THREAD

**Issue by hamidqp** [badfarm/zanzara#43]
when user wants to share his contact with keyboard button it gets force reply to the message own that keyboard and within conversation its sometimes necessary 

[src/Zanzara/Listener/ListenerResolver.php#L60](https://github.com/badfarm/zanzara/blob/17ecdadfd0e06721f1e3672f5e41e69995772456/src/Zanzara/Listener/ListenerResolver.php#L60)

**Comment by cheeghi** [comment]
Hi, I'm sorry but I didn't get the point. The workflow is:

1. the bot starts a conversation
2. the bot sends a ReplyKeyboardMarkup with a button asking for the user's contact
3. the user presses the button and sends the contact to the bot, force-replying the previous bot's message
4. ... and now?

Where is the problem..? Could you add some details? Thankss

**Comment by hamidqp** [comment]
As in the title, that message wont get to the listener because it's reply
message type, not Message

**Comment by cheeghi** [comment]
I released a **0.7.1** with the fix. If you could try it and verify the fix it would be awesome, thank you for the report!
