### ISSUE TITLE
Telegram update TypeError logs

### ISSUE THREAD

**Issue by hamidqp** [badfarm/zanzara#46]
Hi, todays the only thing i get from logs are bunch of these, but idk what could cause this problem, I guess the more users bot have the more these logs showing up.
Also im using the [tdlight telegram bot api](https://github.com/tdlight-team/tdlight-telegram-bot-api).

```
Failed to process Telegram update , reason: TypeError: Zanzara\Telegram\Type\Update::getUpdateType(): Return value must be of type string, null returned in /vendor/badfarm/zanzara/src/Zanzara/Telegram/Type/Update.php:339
Stack trace:
#0 /vendor/badfarm/zanzara/src/Zanzara/Listener/ListenerResolver.php(34): Zanzara\Telegram\Type\Update->getUpdateType()
#1 /vendor/badfarm/zanzara/src/Zanzara/UpdateMode/UpdateMode.php(88): Zanzara\Listener\ListenerResolver->resolveListeners()
#2 /vendor/badfarm/zanzara/src/Zanzara/UpdateMode/Polling.php(78): Zanzara\UpdateMode\UpdateMode->processUpdate()
#3 /vendor/react/promise/src/FulfilledPromise.php(28): Zanzara\UpdateMode\Polling->Zanzara\UpdateMode\{closure}()
#4 /vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then()
#5 /vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
...
```

**Comment by awohsen** [comment]
Hello, I have very same problem but it comes from nowhere! there is no new messages that cause this and i guess maybe just because the response of the get update is weird it pop this out.

**Comment by awohsen** [comment]
![image](https://user-images.githubusercontent.com/93778317/165322651-ad19d12d-ab39-48c4-b910-f9259176023a.png)

I did find one of them! by placing var_dump before mapping.

[ChatJoinRequest](https://core.telegram.org/bots/api#chatjoinrequest) That came on from [Bot API 5.4](https://core.telegram.org/bots/api-changelog#november-5-2021)

**Comment by awohsen** [comment]
![image](https://user-images.githubusercontent.com/93778317/165327192-54541f83-8914-4d94-968f-4e69ba8d185d.png)

Another one from [ChatMemberUpdated](https://core.telegram.org/bots/api#chatmemberupdated) introduced in [Bot API 5.1](https://core.telegram.org/bots/api-changelog#march-9-2021)

**Comment by awohsen** [comment]
So it's not about the new not managed update types(since they are imported already), we need to have custom listeners for each one of the update types or at least help them go throw the global onUpdate listener.

Updates like the two above I mentioned are not getting to onUpdate because they don't get initialized on [getUpdateType](https://github.com/badfarm/zanzara/blob/f190434977494e4430d810d64feff1df8a620767/src/Zanzara/Telegram/Type/Update.php#L345).
