### ISSUE TITLE
BOT API 5.5 

### ISSUE THREAD

**Issue by j3XeZ** [badfarm/zanzara#54]
Hey badfram, Thanks for your work!

Whether features are coming soon 5.5. version of the bot api?

**Comment by cheeghi** [comment]
Hi, yes. We are going to implement that in the next few days

**Comment by j3XeZ** [comment]
Thank you, we will wait

**Comment by j3XeZ** [comment]
> Hi, yes. We are going to implement that in the next few days

Thank you, we will wait

**Comment by cheeghi** [comment]
We released Zanzara `0.8.0` with support for Telegram Bot Api 5.5.
