### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Shoteexke** [badfarm/zanzara#56]
a message keeps returning infinitely a few times when I run my bot.php, normal ? 

message:

Zanzara is listening...
Failed to call Telegram Bot Api, method: getUpdates, params: {
    "offset": 1,
    "limit": 100,
    "timeout": 50,
    "allowed_updates": []
}, reason: {"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}

**Comment by musobekmadrimov** [comment]
Hi, you are running on more than one server, so you are running bot:start command more than one device.
