### ISSUE TITLE
{"error_code":409,"description":"Conflict:

### ISSUE THREAD

**Issue by Shoteexke** [badfarm/zanzara#60]
My code - part of the code:

$bot->onCommand('start', function (Context $ctx) {
    $chat_id = $ctx->getEffectiveChat()->getId();
    $ctx->sendMessage("How to edit sent message?")->then(
    function (\Zanzara\Telegram\Type\Message $msg) use ($ctx, $chat_id) {
        $ctx->editMessageText("Just like this...", ['chat_id'=>$chat_id,'message_id' => $msg->getMessageId()]);
    }
);

Terminal response:

Zanzara is listening...
Failed to call Telegram Bot Api, method: getUpdates, params: {
    "offset": 1,
    "limit": 100,
    "timeout": 50,
    "allowed_updates": []
}, reason: {"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}

1. am i doing something wrong?

**Comment by awohsen** [comment]
Hi, as the error says there is some another getUpdate requests that making this conflict; you can revoke your bot token in the last shot to get rid of it.
