### ISSUE TITLE
Help | bugs / question

### ISSUE THREAD

**Issue by MaxEncryptPHP** [badfarm/zanzara#64]
![Screenshot_20220409-010122_Code Editor](https://user-images.githubusercontent.com/103268469/162555513-b52fa5f6-9ecf-42e3-8698-e0d68c764508.png)

Help me

**Comment by MaxEncryptPHP** [comment]
> ![Screenshot_20220409-010122_Code Editor](https://user-images.githubusercontent.com/103268469/162555513-b52fa5f6-9ecf-42e3-8698-e0d68c764508.png)
> 
> Help me

![Screenshot_20220409-010248_Termux](https://user-images.githubusercontent.com/103268469/162555538-d6cf0b96-5e2f-4970-80fa-568f80391daf.png)


Response of terminal:

**Comment by awohsen** [comment]
Its looks like that I guess you have delayed or bad internet connection.

Also there is time limit for answering the cbquery after inline button is pressed so if you clicked on button and started the bot later it wont let you to answer that.
