### ISSUE TITLE
[Question] Wich EventLoop Should I Use

### ISSUE THREAD

**Issue by awohsen** [badfarm/zanzara#67]
Hi, I am in a scenario where i have 3 reactphp async libraries including Zanzara; The two others are [reactphp-redis](https://github.com/clue/reactphp-redis) & [async mysql](https://github.com/friends-of-reactphp/mysql).
As [Clue](https://github.com/clue) mentioned in both libraries I should not provide the custom event loop unless I know what I'm doing! but i don't know right now! 

Should i provide all 3 of them same event loop? what is the logic behind if i don't !?

Thanks I'm kind of new to all these async magics...

**Comment by cheeghi** [comment]
Hi, the loop should be instanced once for application. Also zanzara allows you to provide a loop if you already have one:

```php
<?php

$config = new Config();
$config->setLoop($loop);

$bot = new Zanzara("token", $config);
```

I would create it at the beginning with `\React\EventLoop\Factory::create()` and pass the reference to the 3 libraries constructor.

**Comment by awohsen** [comment]
Thanks, also I did notice the next loops that are being created in that instance would not work either; so I should use one.
