### ISSUE TITLE
how to drop all updates on long-polling mode?

### ISSUE THREAD

**Issue by parmonov98** [badfarm/zanzara#70]
whenever I send a message previous last stuck message is processed, what I want is to clear up all update so I can work with latest update. 

```
`"badfarm/zanzara": "^0.8.0",

"vlucas/phpdotenv": "^5.4",

"monolog/monolog": "^2.7",

"react/async": "^3.0.0"`
```

**Comment by awohsen** [comment]
Use this line before `$bot->run();` 
(hopefully this would reach telegram sooner than Zanzara pull requests, or you can use promises!)

```php
$bot->getTelegram()->deleteWebhook(['drop_pending_updates' => true]);
```
