### ISSUE TITLE
Bot stops working in server

### ISSUE THREAD

**Issue by musobekmadrimov** [badfarm/zanzara#77]
Hello, everyone. Now I am facing to a problem that after some time my bot stops working on server without any reason. 

I used 

`nohup php artisan bot:start </dev/null &>/dev/null &`

command and it is working some time, but after 2 or 3 days it stops working. I asked help from hosting service support, but they say problem is not on the server, it is in my code. 

HELP, PLEASE!

**Comment by awohsen** [comment]
Hi, I'm facing the same issue with pulling mode.
