### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by foremtehan** [badfarm/zanzara#8]
Hello folks Are there any plans to support PHP 8?

**Comment by cheeghi** [comment]
Yes, we opened a [branch](https://github.com/badfarm/zanzara/tree/feature/php-8) to work on that. Right now we have 2 problems that prevent us to upgrade:
* [reactphp/filesystem](https://github.com/reactphp/filesystem) currently doesn't support php 8. I have already opened an [issue](https://github.com/reactphp/filesystem/issues/89) and they are working on it
* [cweiske/jsonmapper](https://github.com/cweiske/jsonmapper) throws some deprecation warning under php 8, also here there's already a [pull request](https://github.com/cweiske/jsonmapper/pull/170)

In the meantime you can use zanzara with php 8 ignoring the platform requirements:
```
composer install --ignore-platform-reqs
```
Except for jsonmapper warnings seems it works fine.

**Comment by cheeghi** [comment]
Support added in 0.6.0
