### ISSUE TITLE
Bot stop working on a server

### ISSUE THREAD

**Issue by evanh-shumakov** [badfarm/zanzara#82]
Bot stop working on a server started as `php start_bot.php` with no log information
Should I make some extra settings for my server?

**Comment by awohsen** [comment]
How often? sometimes it stops pulling updates but there was always an error log like time out. Personally, I use webhook with ReactPHP and TDLight bot API server and seems no problem.

**Comment by evanh-shumakov** [comment]
I think, it stops every three days (proximetly)

**Comment by awohsen** [comment]
try this: 
```php
$config->setPollingRetry(10);
$config->setPollingTimeout(120);
```
If didn't help, try using [TDLight Telegram Bot API](https://github.com/tdlight-team/tdlight-telegram-bot-api) or [Telegram Bot API](https://github.com/tdlib/telegram-bot-api) server itself: 
$config->setApiTelegramUrl('http://127.0.0.1:8580'); // local bot API server port

This might be helpful as well:
```
[Unit]
Description=Telegram-bot-api server
Wants=network-online.target
After=network.target network-online.target
StartLimitIntervalSec=60
[Service]
Type=simple
Restart=always
RestartSec=1
User=bots
ExecStart=/usr/bin/telegram-bot-api --api-id=API_ID --api-hash=API_HASH --local --http-port=8580 --dir=/home/bots/telegram-bot-api --allow-users -v1

[Install]
WantedBy=multi-user.target
```

**Comment by evanh-shumakov** [comment]
> ```
> $config->setApiTelegramUrl('http://127.0.0.1:8580'); // local bot API server port
> ```
Tryed `$config->setPollingRetry(10); $config->setPollingTimeout(120);` - haven't helped. The bot have collupsed again after 3 days.

Try `$config->setApiTelegramUrl('http://127.0.0.1:8580');` and get an error "Failed to call Telegram Bot Api, method: getWebhookInfo, params: [], reason: RuntimeException: Connection to tcp://127.0.0.1:8580 failed: Connection refused (ECONNREFUSED) in /vendor/react/socket/src/TcpConnector.php:140"

**Comment by awohsen** [comment]
You should install it and set it on that specific port, follow this [build instructions generator](https://tdlight-team.github.io/tdlight-telegram-bot-api/build.html)

If you don't get it read about it [here : Using a Local Bot API Server)](https://core.telegram.org/bots/api#using-a-local-bot-api-server) and [here: Local Bot API Server Usage](https://github.com/tdlight-team/tdlight-telegram-bot-api#usage).

**Comment by evanh-shumakov** [comment]
Thank you so much, and I really sorry: I use a virtual hosting for my projects, and, as it turned out, it is not permitted to use any kind of bots, so they just stoped it forced.
Thank you again for your help : )

**Comment by evanh-shumakov** [comment]
> You should install it and set it on that specific port, follow this [build instructions generator](https://tdlight-team.github.io/tdlight-telegram-bot-api/build.html)
> 
> If you don't get it read about it [here : Using a Local Bot API Server)](https://core.telegram.org/bots/api#using-a-local-bot-api-server) and [here: Local Bot API Server Usage](https://github.com/tdlight-team/tdlight-telegram-bot-api#usage).

Thank you so much, and I really sorry: I use a virtual hosting for my projects, and, as it turned out, it is not permitted to use any kind of bots, so they just stoped it forced.
Thank you again for your help : )
